chezzionwebapp/chezzionwebapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('nonsap.urls', 'nonsap'), namespace='nonsap')),
]

chezzionwebapp/nonsap/urls.py
from django.urls import path, include
from .views import authView, home, dashboard_view, logout_view, staff_login_view, superadmin_login_view
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import all_data, export_issues_csv  
from .views import profile, change_password
from .views import upload_issues
from .views import chardet

app_name = 'nonsap'




urlpatterns = [
    path('', views.user_redirect, name='user_redirect'),
    path('home', views.home, name='home'),
    path('superadmin/', views.superadmin_dashboard, name='superadmin_dashboard'), 
    path("register/", authView, name="register"),  
    path('accounts/', include('django.contrib.auth.urls')),  
    path('accounts/logout/', logout_view, name='logout'),
    path('incident-management/dashboard/', dashboard_view, name='dashboard'),
    path('staff-admin/admin-dashboard/', views.admin_dashboard, name='admin-dashboard'),  
    path('incident-management/raise-issue/', views.raise_issue, name='raise-issue'),
    path('incident-management/success/<int:issue_id>/', views.success, name='success'),
    path('staff-admin/view-assigned/', views.assigned_complaints, name='assigned_complaints'),
    path('incident-management/view-status/<int:issue_id>/', views.view_status, name='view_status'),
    path('superuser/', views.superadmin_dashboard, name='superadmin_dashboard'),
    path('superuser/view-issue/<int:issue_id>/', views.view_issue, name='view_issue'),
    path('assign-staff/<int:issue_id>/', views.assign_staff, name='assign_staff'),
    path('staff-admin/viewdetails/<int:issue_id>/', views.view_details, name='view_details'),
    path('update-status/<int:issue_id>/', views.update_status, name='update_status'),
    path('superadmin-login/', views.superadmin_login_view, name='superadmin_login'),
    path('staff-login/', views.staff_login_view, name='staff_login'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('update_rootcause/<int:issue_id>/', views.update_rootcause, name='update_rootcause'),
    path('update_priority/<int:issue_id>/', views.update_priority, name='update_priority'),
    path('profile/', profile, name='profile'),
    path("pwa/", include("pwa.urls")),
    path("", include("pwa.urls")), 
    path("superuser/all/", views.all_data, name='all_data'),
    path('export-issues-csv/', export_issues_csv, name='export_issues_csv'),
    path('profile/change-password/', change_password, name='change_password'),
    path('upload/', upload_issues, name='upload_issues')


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chezzionwebapp/nonsap/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.models import User
from .forms import IncidentIssueForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import IncidentIssue, Comment
from .forms import CommentForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Issue, User 
from .models import Issue  
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from .models import Attachment
from django.urls import path
from .models import IncidentIssue, User
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.db.models import F
from .forms import StaffLoginForm, SuperAdminLoginForm
from django.shortcuts import redirect
from django.contrib.auth.models import Group
import logging
from .forms import ChangePasswordForm

# Set up the logger
logger = logging.getLogger(__name__)

from datetime import timedelta
# Home view
@login_required
def home(request):
    return render(request, 'home.html')


@login_required
def welcome_view(request):
    return render(request, 'home.html', {'username': request.user.username})

# Sign-up view
def authView(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')  # Redirect to the login page after successful signup
    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form': form})

# Logout view
def logout_view(request):
    # Check if the user is superuser, staff, or regular user
    if request.user.is_superuser:
        logout(request)
        return redirect('superadmin_login')  # Redirect to superuser dashboard
    elif request.user.is_staff:
        logout(request)
        return redirect('staff_login')  # Redirect to staff dashboard
    else:
        logout(request)
        return redirect('login')# Ensure 'login' URL exists in urls.py

# Login form class
class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


def authenticate_user(request, username, password):
    user = authenticate(request, username=username, password=password)
    if user is not None:
        print(f"Authenticated user: {user.username}")  # Debugging
        login(request, user)
        return redirect(get_redirect_url(user))
    return None


# Login viewfrom django.contrib import messages




def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            # Redirect based on user role
            if user.is_superuser:
                return redirect("superadmin_dashboard")  # Change this to the actual URL name
            elif user.is_staff:
                return redirect("admin_dashboard")  # Change this to the actual URL name
            else:
                return redirect("home")  # Change this to the actual home URL name
        else:
            error_message = "Invalid username or password."

    else:
        error_message = None

    return render(request, "login.html", {"error_message": error_message})




# Helper function for determining redirection URLimport logging

from django.urls import reverse

def get_redirect_url(user):
    if user.is_superuser:
        return reverse('superadmin_dashboard')  # assuming you have a named URL
    elif user.is_staff:
        return reverse('admin_dashboard')
    else:
        return reverse('home')




@login_required
def admin_dashboard(request):
    return render(request, 'admin/admin-dashboard.html')

# Superadmin check
def is_superadmin(user):
    return user.is_superuser

@login_required
@user_passes_test(is_superadmin, login_url='login')  # Specify login_url for unauthorized access
def superadmin_dashboard(request):
    return render(request, 'master/superadmin_dashboard.html', {})

# Incident Issue form handling view

import logging
logger = logging.getLogger(__name__)



@login_required
def raise_issue(request):
    if request.method == 'POST':
        form = IncidentIssueForm(request.POST, request.FILES)
        files = request.FILES.getlist('attachment')  # Get all uploaded files
        if form.is_valid():
            # Create the issue object and save it
            incident_issue = form.save(commit=False)
            incident_issue.reporter = request.user
            incident_issue.save()

            # Save the attachments in the `nonsap_attachment` table
            for file in files:
                Attachment.objects.create(
                    file=file,  # Store the file name
                    issue_id=incident_issue.id,  # Link the attachment to the issue
                    uploaded_at=now()
                )

            # Send email notification to the reporter
            login_link = "https://staging.chezzion.com/superadmin-login/"
            try:
                send_mail(
                    'Issue Reported Successfully',
                    f'Your issue "{incident_issue.issue}" has been successfully reported. We will send you an email once it is resolved.',
                    settings.DEFAULT_FROM_EMAIL,
                    [request.user.email],
                    fail_silently=False,
                )
            except Exception as e:
                print(f"Error sending email to reporter: {e}")
                logger.error(f"Error sending email to reporter: {e}")

            # Get emails of all superadmins and send one email to all of them
            superadmins = User.objects.filter(is_superuser=True)
            superadmin_emails = [admin.email for admin in superadmins]
            print(f"Superadmin emails: {superadmin_emails}")  # Debugging line

            try:
                send_mail(
                    'New Issue Reported',
                    f'A new issue "{incident_issue.issue}" has been reported by {incident_issue.reporter.username}. Complaint Number:  {incident_issue.custom_id}\n\nTo view and manage this issue, please login here: {login_link}',
                    settings.DEFAULT_FROM_EMAIL,
                    superadmin_emails,  # Send to all superadmins at once
                    fail_silently=False,
                )
            except Exception as e:
                print(f"Error sending email to superadmins: {e}")
                logger.error(f"Error sending email to superadmins: {e}")

            # Success message and redirect
            messages.success(request, f'Issue "{incident_issue.issue}" has been reported successfully!')
            return redirect('nonsap:success', issue_id=incident_issue.id)

        else:
            messages.error(request, 'There was an error with your form submission. Please try again.')
    else:
        form = IncidentIssueForm()

    return render(request, 'incident-management/raise-issue.html', {'form': form})




def success(request, issue_id):
    issue = get_object_or_404(IncidentIssue, id=issue_id)
    return render(request, 'incident-management/success.html', {'issue': issue})





from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render
from django.db.models import Q
from .models import IncidentIssue

@login_required
def dashboard_view(request):
    status_filter = request.GET.get('status', 'all')
    priority = request.GET.get('priority', 'all')

    issues = IncidentIssue.objects.filter(reporter=request.user).order_by('-report_date', '-report_time') 

    # Status filtering
    if status_filter == 'active':
        issues = issues.filter(status='active')
    elif status_filter == 'inprogress':
        issues = issues.filter(status='inprogress')
    elif status_filter == 'resolved':
        issues = issues.filter(status='resolved')

    # Priority filtering
    if priority == 'critical':
        issues = issues.filter(Q(status='active') | Q(status='inprogress'), priority='P0')

    # Pagination
    paginator = Paginator(issues, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Stats
    total_issues = IncidentIssue.objects.filter(reporter=request.user).count()
    active_issues = IncidentIssue.objects.filter(reporter=request.user, status='active').count()
    resolved_issues = IncidentIssue.objects.filter(reporter=request.user, status='resolved').count()
    critical_issues = IncidentIssue.objects.filter(reporter=request.user, priority='P0', status__in=['active', 'inprogress']).count()
    inprogress_issues = IncidentIssue.objects.filter(reporter=request.user, status='inprogress').count()


    return render(
        request,
        'incident-management/dashboard.html',
        {
            'username': request.user.username,
            'issues': page_obj,
            'total_issues': total_issues,
            'active_issues': active_issues,
            'resolved_issues': resolved_issues,
            'critical_issues': critical_issues,
            'inprogress_issues': inprogress_issues,
            'status_filter': status_filter,
            'priority': priority
        }
    )






from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

chezzionwebapp/nonsap/templates/admin-base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Chezzion Web app{% endblock %}</title>
    {% load static %}
    {% load tz %}
    {% load pwa %}
    <meta name="theme-color" content="#ffffff">
    <!-- PWA Icons -->
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/logo-icon.png' %}">
    <link rel="icon" type="image/png" sizes="512x512" href="{% static 'icons/logo-icon.png' %}">

    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logo-icon.png' %}">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'assets/img/fav-icon.png' %}" type="image/x-icon">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- Bootstrap Datepicker CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.9.0/dist/css/bootstrap-datepicker.min.css"
        rel="stylesheet">

    <!-- Bootstrap Timepicker CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <!-- jq-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="manifest" href="{% static 'pwa/manifest.json' %}">
    <script>
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register("{% static 'assets/js/serviceworker.js' %}")
                .then(function (registration) {
                    console.log('Service Worker registered with scope:', registration.scope);
                })
                .catch(function (error) {
                    console.log('Service Worker registration failed:', error);
                });
        }
    </script>
</head>

<body>

    {% if user.is_authenticated %}
    <nav class="navbar bg-light navbar-expand-md">
        <div class="container">
            <a class="navbar-brand" href="{% url 'nonsap:admin-dashboard' %}">
                <img class="nav-logo" src="{% static 'assets/img/logo-icon.png' %}" alt="logo">
            </a>
            <button class="navbar-toggler text-dark custom-navbar" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#navbarOffcanvas" aria-controls="navbarOffcanvas" aria-expanded="false"
                aria-label="Toggle navigation menu">
                <i class="fa-solid fa-sliders"></i>
            </button>
            <div class="offcanvas offcanvas-end" id="navbarOffcanvas" tabindex="-1"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{{ request.user.username }}</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="navbar-nav justify-content-end flex-grow-1 pe-3 text-dark">
                        <a class="nav-item nav-link" href="{% url 'nonsap:admin-dashboard' %}">
                            <span><i class="fa-solid fa-gauge"></i></span> Dashboard
                        </a>
                        <a class="nav-item nav-link" href="{% url 'nonsap:assigned_complaints' %}">
                            <span><i class="fa-solid fa-list-check"></i></span> View Issues Assigned
                        </a>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                <i class="fa-solid fa-user"></i> {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'nonsap:profile' %}">Profile</a></li>
                                <li>
                                    <form method="POST" action="{% url 'nonsap:logout' %}"
                                        class="d-flex align-items-center" id="logout-form">
                                        {% csrf_token %}
                                        <button type="button" class="dropdown-item " onclick="confirmLogout()">
                                            Logout <i class="fa-solid fa-right-from-bracket"></i>
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% endif %}

    {% block start %}
    {% endblock %}
    <footer class="">
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 mx-auto text-center">
                    <p>&copy; 2025 <a class="text-decoration-none fw-bold" href="https://chezzion.com"
                            target="_blank">Chezzion.</a> All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'assets/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
    <script>
        let sortDirection = {};

        function sortTable(columnIndex, tableId) {
            let table = document.getElementById(tableId);
            let tbody = table.querySelector("tbody");
            let rows = Array.from(tbody.querySelectorAll("tr"));

            // Initialize sort direction if not set
            if (sortDirection[columnIndex] === undefined) {
                sortDirection[columnIndex] = true;  // Ascending by default
            } else {
                sortDirection[columnIndex] = !sortDirection[columnIndex];  // Toggle direction
            }

            rows.sort((rowA, rowB) => {
                let cellA = rowA.cells[columnIndex].textContent.trim();
                let cellB = rowB.cells[columnIndex].textContent.trim();

                // Convert numbers for correct sorting
                let isNumeric = !isNaN(cellA) && !isNaN(cellB);
                if (isNumeric) {
                    return sortDirection[columnIndex] ? cellA - cellB : cellB - cellA;
                }

                return sortDirection[columnIndex] ? cellA.localeCompare(cellB) : cellB.localeCompare(cellA);
            });

            // Append sorted rows back to tbody
            tbody.innerHTML = "";
            rows.forEach(row => tbody.appendChild(row));

            // Update sort icons
            updateSortIcons(columnIndex, tableId);
        }

        function updateSortIcons(columnIndex, tableId) {
            // Reset all icons
            for (let i = 0; i < 5; i++) {
                let icon = document.getElementById("sort-icon-" + i);
                icon.classList.remove("fa-arrow-up", "fa-arrow-down");
                icon.classList.add("fa-sort");  // Add default sort icon
            }

            // Update the icon based on the sort direction
            let icon = document.getElementById("sort-icon-" + columnIndex);
            if (sortDirection[columnIndex]) {
                icon.classList.remove("fa-sort");
                icon.classList.add("fa-arrow-up");
            } else {
                icon.classList.remove("fa-sort");
                icon.classList.add("fa-arrow-down");
            }
        }
    </script>
</body>

</html>

chezzionwebapp/nonsap/templates/home.html
{% extends "base.html" %}
{% block start %}
{% if request.user.is_authenticated %}
<h2 class="text-center text-primary mt-5">
    Hi, {{ request.user.username }}
</h2>
<div class="container text-center p-5">
    <h3>Welcome to the Incident Management & Complaint Raise Portal</h3>
    <h6>Efficient Issue Resolution for All Users</h6>

    <p> At Chezzion, we value the quality of service we provide to our customers and employees. Our Incident
        Management Portal is designed to ensure that any issues or complaints are addressed quickly and efficiently.

        Whether you're facing a technical issue, a service-related problem, or any other type of complaint, we are here
        to help.
        Through this portal, you can easily raise and track your complaints, ensuring you are always in the loop about
        the
        resolution process.</p>
    <a href="{% url 'nonsap:dashboard' %}" class="btn btn-secondary"> Go to Dashboard </a>
</div>
{% else %}
<h2 class="text-center text-danger mt-5">
    Login
</h2>
{% endif %}


{% endblock %}

chezzionwebapp/nonsap/templates/superuser-base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Chezzion Web app{% endblock %}</title>
    {% load static %}
    {% load tz %}
    {% load pwa %}
    <meta name="theme-color" content="#ffffff">
    <!-- PWA Icons -->
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/logo-icon.png' %}">
    <link rel="icon" type="image/png" sizes="512x512" href="{% static 'icons/logo-icon.png' %}">

    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logo-icon.png' %}">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'assets/img/fav-icon.png' %}" type="image/x-icon">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- Bootstrap Datepicker CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.9.0/dist/css/bootstrap-datepicker.min.css"
        rel="stylesheet">

    <!-- Bootstrap Timepicker CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-timepicker/css/bootstrap-timepicker.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

    <!-- jq-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="manifest" href="{% static 'pwa/manifest.json' %}">
    <script>
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register("{% static 'assets/js/serviceworker.js' %}")
                .then(function (registration) {
                    console.log('Service Worker registered with scope:', registration.scope);
                })
                .catch(function (error) {
                    console.log('Service Worker registration failed:', error);
                });
        }
    </script>

</head>

<body>

    {% if user.is_authenticated %}
    <nav class="navbar bg-light navbar-expand-md">
        <div class="container">
            <a class="navbar-brand" href="{% url 'nonsap:superadmin_dashboard' %}">
                <img class="nav-logo" src="{% static 'assets/img/logo-icon.png' %}" alt="logo">
            </a>
            <button class="navbar-toggler text-dark custom-navbar" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#navbarOffcanvas" aria-controls="navbarOffcanvas" aria-expanded="false"
                aria-label="Toggle navigation menu">
                <i class="fa-solid fa-sliders"></i>
            </button>
            <div class="offcanvas offcanvas-end" id="navbarOffcanvas" tabindex="-1"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{{ request.user.username }}</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="navbar-nav justify-content-end flex-grow-1 pe-3 text-dark">
                        <a class="nav-item nav-link" href="{% url 'nonsap:superadmin_dashboard' %}">
                            <span><i class="fa-solid fa-gauge"></i></span> Dashboard
                        </a>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                <i class="fa-solid fa-user"></i> {{ request.user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'nonsap:profile' %}">Profile</a></li>
                                <li>
                                    <form method="POST" action="{% url 'nonsap:logout' %}"
                                        class="d-flex align-items-center" id="logout-form">
                                        {% csrf_token %}
                                        <a class="dropdown-item" type="button" class="btn btn-link "
                                            onclick="confirmLogout()">
                                            Logout <i class="fa-solid fa-right-from-bracket"></i>
                                        </a>
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% endif %}

    {% block start %}
    {% endblock %}
    <footer class="">
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 mx-auto text-center">
                    <p>&copy; 2025 <a class="text-decoration-none fw-bold" href="https://chezzion.com"
                            target="_blank">Chezzion.</a> All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'assets/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
    <script>
        let sortDirection = {};

        function sortTable(columnIndex, tableId) {
            let table = document.getElementById(tableId);
            let tbody = table.querySelector("tbody");
            let rows = Array.from(tbody.querySelectorAll("tr"));

            // Initialize sort direction if not set
            if (sortDirection[columnIndex] === undefined) {
                sortDirection[columnIndex] = true;  // Ascending by default
            } else {
                sortDirection[columnIndex] = !sortDirection[columnIndex];  // Toggle direction
            }

            rows.sort((rowA, rowB) => {
                let cellA = rowA.cells[columnIndex].textContent.trim();
                let cellB = rowB.cells[columnIndex].textContent.trim();

                // Convert numbers for correct sorting
                let isNumeric = !isNaN(cellA) && !isNaN(cellB);
                if (isNumeric) {
                    return sortDirection[columnIndex] ? cellA - cellB : cellB - cellA;
                }

                return sortDirection[columnIndex] ? cellA.localeCompare(cellB) : cellB.localeCompare(cellA);
            });

            // Append sorted rows back to tbody
            tbody.innerHTML = "";
            rows.forEach(row => tbody.appendChild(row));

            // Update sort icons
            updateSortIcons(columnIndex, tableId);
        }

        function updateSortIcons(columnIndex, tableId) {
            // Reset all icons
            for (let i = 0; i < 5; i++) {
                let icon = document.getElementById("sort-icon-" + i);
                icon.classList.remove("fa-arrow-up", "fa-arrow-down");
                icon.classList.add("fa-sort");  // Add default sort icon
            }

            // Update the icon based on the sort direction
            let icon = document.getElementById("sort-icon-" + columnIndex);
            if (sortDirection[columnIndex]) {
                icon.classList.remove("fa-sort");
                icon.classList.add("fa-arrow-up");
            } else {
                icon.classList.remove("fa-sort");
                icon.classList.add("fa-arrow-down");
            }
        }
    </script>
</body>

</html>

chezzionwebapp/nonsap/templates/welcome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chezzion App</title>
    {% load static %}
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
</head>

<body>
    welcome to chezzion
</body>

</html>